### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by thysultan** [Andarist/stylis-plugin-extra-scope#1]
There are few cases where this might fail, specifically around \@at-rules.

Related test case:

```css
var sample =`
div, h1 {
  span {
    font-size: 14px;
  }
  background-color: rebeccapurple;
}

@media {
  .other-class {
    margin: 20px;
  }
}

@keyframe {
  0%: {color: red}
}
```
That said i think something like following should handle all of them.

```js
function extraScopePlugin (context, content, selector, parents, line, column, length, type) {
  if (context === 2 && type !== 107)
    for (var i = 0; i < selector.length; i++)
      selector[i] = '#body ' + selector[i]
}
```

Related https://github.com/thysultan/stylis.js/issues/102#issuecomment-378317363
